### ISSUE TITLE
Copy as Markdown not escaping some characters

### ISSUE THREAD

**Issue by q00u** [BlackGlory/copycat#5]
If the text itself includes asterisks or angle-brackets, they aren't escaped into \* or &lt; &gt;

So the resulting markdown doesn't match the original. That is to say, this italicized and censored internal thought:
*F\*ck, what is going on?*
becomes:
*F*ck, what is going on?*
The asterisk in the text isn't escaped, so it's treated as markdown when it shouldn't be.

This looks like it might be a Turndown issue, as escaping was fixed in the recent 5.0.0 release, so if you're using a version older than that you'll have the same bugs.

**Comment by BlackGlory** [comment]
It's obviously confusing to ask an error about Markdown on a platform that supports Markdown, so I tried to display these in code syntax:

original HTML

```html
<em>F*ck, what is going on?</em>
```

should be

```markdown
*F\*ck, what is going on?*
```

not

```markdown
*F*ck, what is going on?*
```

After my check, this is indeed a problem with Turndown. When I upgraded to Turndown 5.0.0, the problem was solved. Thank you for your reminder, please wait for me to release Copycat 2.4.1.

**Comment by q00u** [comment]
Still not escaping angle brackets.

Original: `<<REBIRTH>>`

Source: `&lt;&lt;REBIRTH&gt;&gt;`

Becomes: `<\>`

and

Original: `<Shield of Sunset Light (Shield) (Set Equipment)>`

Source: `&lt;Shield of Sunset Light (Shield) (Set Equipment)&gt;`

Becomes: ....nothing.

I did see a comment talking about [more aggressive escaping rules](https://github.com/domchristie/turndown/issues/233#issuecomment-399098714) (which included angle brackets) which didn't make it into the 5.0.0 release, so maybe it's possible with that custom rule?

Currently, if the formatted text includes `&lt;` and `&gt;`, it's misinterpreted as an HTML tag at some point along the way, and removed.

**Comment by BlackGlory** [comment]
Copycat will decode HTML character entities into ordinary characters in advance, which causes this problem. After I removed the code that decoded HTML entities, the problem was solved, it will be released as version 2.4.2.
